type Product = {
  id: string;
  name: string;
  description: string;
  link: string;
  price: number;
  shape: string;
  controls: string;
  feature: string[];
  eartip: string;
  batt_life_bud: number;
  batt_life_case: number;
  wingtips: string;
  release_year: string;
  water_dust_resist: string;
  codecs: string[];
  min_latency: number;
  company: string;
  sentiment: string;
  product_image_url: string;
  wishlist: Wishlist;
};
